events/event/urls.py
from django.urls import path

from . import views


app_name = 'event'

urlpatterns = [
    path('events/', views.EventList.as_view(), name='event_list'),
    # path('events/<int:id>', views.event_detail, name='event_detail'),
    path('events/<int:pk>', views.ShowEvent.as_view(), name='event_detail'),
    path('events/add', views.AddEvent.as_view(), name='event_add'),
    path('edit/<int:pk>', views.UpdateEvent.as_view(), name='event_update'),
    path('delete/<int:pk>', views.DeleteEvent.as_view(), name='event_delete'),
    path('contact/', views.contact_view, name='contact'),
    path('success/', views.success_view, name='success'),


]

events/events/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('event.urls', namespace='event')),
    path('tinymce/', include('tinymce.urls')),
]

events/event/models.py
from django.db import models
from tinymce import models as tinymce_models


class Event(models.Model):
    title = models.CharField(max_length=100, verbose_name='Название')
    # description = models.TextField(verbose_name='Описание')
    description = tinymce_models.HTMLField()

    date_time = models.DateTimeField(verbose_name='Дата')
    location = models.CharField(max_length=100, verbose_name='Место')

events/event/forms.py
from django import forms
from .models import Event


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = '__all__'


class AddEventForm(forms.ModelForm):

    # title = forms.CharField(max_length=100, label='Название')
    # description = forms.CharField(widget=forms.Textarea, label='Описание')
    # date_time = forms.DateTimeField(widget=forms.SelectDateWidget, label='Дата')
    date_time = forms.DateTimeField(widget=forms.SplitDateTimeWidget(
        date_attrs={'type': 'date'},
        time_attrs={'type': 'time'}
    ))

    # # time_of_day = forms.DateTimeField(widget=forms.TimeInput, label='Время')
    # location = forms.CharField(max_length=100, label='Место')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # it is required to set it False,
        # otherwise it will throw error in console
        self.fields["description"].required = False

    class Meta:
        model = Event
        fields = '__all__'


class ContactForm(forms.Form):
    from_email = forms.EmailField(label='Email', required=True)
    subject = forms.CharField(label='Тема', required=True)
    message = forms.CharField(label='Сообщение', widget=forms.Textarea, required=True)

events/event/views.py
# from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import DetailView, ListView
from django.urls import reverse_lazy
from .forms import AddEventForm
from .models import Event

from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .forms import ContactForm
from events.settings import RECIPIENTS_EMAIL, DEFAULT_FROM_EMAIL


class EventList(ListView):
    model = Event
    template_name = 'event/list.html'
    context_object_name = 'events'
    paginate_by = 2


class ShowEvent(DetailView):
    model = Event
    template_name = 'event/detail.html'


class AddEvent(CreateView):
    model = Event
    form_class = AddEventForm
    template_name = 'event/add.html'
    success_url = reverse_lazy('event:event_list')


class UpdateEvent(UpdateView):
    model = Event
    form_class = AddEventForm
    # fields = '__all__'
    template_name = 'event/edit.html'
    success_url = reverse_lazy('event:event_list')


class DeleteEvent(DeleteView):
    model = Event
    template_name = 'event/delete.html'
    context_object_name = 'event'
    success_url = reverse_lazy('event:event_list')


def contact_view(request):
    # если метод GET, вернем форму
    if request.method == 'GET':
        form = ContactForm()
    elif request.method == 'POST':
        # если метод POST, проверим форму и отправим письмо
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                send_mail(f'{subject} от {from_email}', message,
                          DEFAULT_FROM_EMAIL, RECIPIENTS_EMAIL)
            except BadHeaderError:
                return HttpResponse('Ошибка в теме письма.')
            return redirect('success')
    else:
        return HttpResponse('Неверный запрос.')
    return render(request, "event/email.html", {'form': form})


def success_view(request):
    return HttpResponse('Приняли! Спасибо за вашу заявку.')

events/event/templates/event/add.html
{% extends "event/base.html" %}

{% block content %}
    <h1>{{ title }}</h1>

    <div>

        <form action="" method="POST">
            {% csrf_token %}
            {{ form.media }}
            <div class="row-form-errors">{{ form.non_field_errors }}</div>
            {% for f in form %}
                <p><label for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
            <div class="row-form-errors">{{ f.errors }}</div>
            {% endfor %}

            <button type="submit">Сохранить</button>
        </form>



    </div>

    <p><a href="{% url 'event:event_list' %}">На главную</a></p>
{% endblock %}

events/event/templates/event/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">
</head>
<body>
<div id="content">
    {% block content %}

    {% endblock %}

    {% block navigation %}
    {% endblock %}
</div>
<div id="sidebar"><h2>EVENTS</h2>
    <p>Календарь событий</p>
    <p><a href="{% url 'event:event_add' %}">Добавить событие</a></p>

</div>
</body>
</html>

events/event/templates/event/delete.html
{% extends "event/base.html" %}

{% block content %}
    <h1>{{ title }}</h1>

    <div>

        <form method="post">{% csrf_token %}
            <p>Удалить событие "{{ event.title }}"?</p>
            <p>Содержание:</p>
            <p>{{ event.description|truncatewords:15|safe }}</p>
            <p><button type="submit">Подтвердить удаление</button></p>
            <p><button type="button" onclick="window.history.back();">Отмена</button></p>
        </form>


    </div>

    <p><a href="{% url 'event:event_list' %}">На главную</a></p>
{% endblock %}

events/event/templates/event/detail.html
{% extends "event/base.html" %}

{% block title %}{{ event.title }}{% endblock %}

{% block content %}
  <h1>{{ event.title }}</h1>
  <p class="date">{{ event.date_time }}</p>
  {{ event.description|safe|linebreaks }}

<a href="{% url 'event:event_list' %}">На главную</a>
{% endblock %}

events/event/templates/event/edit.html
{% extends "event/base.html" %}

{% block content %}
    <h1>{{ title }}</h1>

    <div>

        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            {{ form.media}}
            <button type="submit">Сохранить</button>
        </form>



    </div>

    <p><a href="{% url 'event:event_list' %}">На главную</a></p>
{% endblock %}

events/event/templates/event/email.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Пример отправки сообщений</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
  <h1 class="text-center">Оставьте заявку</h1>
  <div class="container text-center">
    <div id="form_container">
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="form-actions form-group ">
          <button type="submit" class="form-control btn btn-success">Отправить</button>
        </div>
      </form>
    </div>
  </div>
</body>
</html>

events/event/templates/event/list.html
{% extends "event/base.html" %}

{% block title %}Events{% endblock %}

{% block content %}
  <h1>Events</h1>
  {% for event in events %}
    <h2>
      <a href="{% url 'event:event_detail' event.id %}">
        {{ event.title }}
      </a>
    </h2>
    <p>{{ event.description|safe }}</p>
    <p class="date">{{ event.date_time }}</p>
    <p>{{ event.location }}</p>
  {% endfor %}
{% endblock %}